### ISSUE TITLE
IT Works but the Keyboard color is only white

### ISSUE THREAD

**Issue by AncalagonTheBlack** [Gibtnix/MSIKLM#12]
Keyboard stays white. Diffrent Modes not working on GE602PC Msi Laptop running linux mint 18.3 x64

**Comment by Gibtnix** [comment]
Don't know for sure what's going wrong... which color configuration do you want to use? I can try to prepare a different version to test if this one is working for you.

**Comment by AncalagonTheBlack** [comment]
for example i try `sudo msiklm red` but it just stays white.

**Comment by Gibtnix** [comment]
Ok, I'll prepare a special version for you to test if this one works... ;-)

**Comment by Gibtnix** [comment]
Coming back to this issue... I've prepared a test version, see the attached version of 'msiklm.c' in the zip file
[msiklm.zip](https://github.com/Gibtnix/MSIKLM/files/1826736/msiklm.zip)
. Please first uninstall any currently installed version, make a fresh checkout of the repo and _replace_ the included file msiklm.c with the one that I've added. Then compile the program in the same way as the original one and try 'sudo ./msiklm green,green,green' and tell me the resulting color :-)

I slightly modified the communication with the keyboard, but I don't know if this will fix the issue - to test it I prepared a version that sets the color to all-green (even if you supply other arguments, it's hard-coded to all green), it works on my side in the same way as the original version does. If this one works for you I can prepare a different version that also allows different options. But first I need to know if this one works. Good luck!

**Comment by AncalagonTheBlack** [comment]
Yeah that works it sets the color to green :D

**Comment by Gibtnix** [comment]
Ok I'll try to prepare a different version then... currently I have to decide how the program should decide between the more functional (but obviously not everywhere working) or the basic (but more compatible) version. For this I need to know two things: First I prepared another version that uses both commands and prints the result onto screen; Please try this version again
[msiklm.zip](https://github.com/Gibtnix/MSIKLM/files/1834767/msiklm.zip)
 and tell me the output that you see on the screen if running 'sudo ./msiklm green'. It should be something like this:

`First return = ...
Second return = ...
First return = ...
Second return = ...
First return = ...
Second return = ...`

I expect the "second return" outputs to print '8' (since they work) but the "first return" outputs might be different.

Further please run 'sudo ./msiklm list > devices.log' which will create a file 'devices.log' that contains information about your SteelSeries MSI keyboard, maybe this contains helpful information as well (feel free to remove any stuff related to other USB devices from this file, I'm only interested in the keyboard's information).

**Comment by AncalagonTheBlack** [comment]
```
First return = 8
Second return = 8
First return = 8
Second return = 8
First return = 8

``
[devices.log](https://github.com/Gibtnix/MSIKLM/files/1844829/devices.log)

Here :D

**Comment by Gibtnix** [comment]
Ok thanks, I will provide a solution for this... ;-)

**Comment by Gibtnix** [comment]
I just updated the version in the repository, if everything works as expected it should fully work for your keyboard as long as you do not use explicit rgb-colors (hex code or [r;g;b]) and always add the brightness command (high, medium, low or off) to the colors. This is important, because otherwise always the rgb-command will be used internally that has not been working on your side. So adding the brightness switches to the working command one, at least as far as I could test it. Please fell free to test different command combinations and give me some feedback it they work.

**Comment by AncalagonTheBlack** [comment]
Works Perfectly Now

**Comment by Gibtnix** [comment]
Glad to hear to, so I will close the issue. Please report a new one if there are any problems.

**Comment by TuxBird** [comment]
> Don't know for sure what's going wrong... which color configuration do you want to use? I can try to prepare a different version to test if this one is working for you.

hey sir i have the same problem with me MSI GP36 Leopard 8re. with the keyboard only showing white

**Comment by Gibtnix** [comment]
Did you also try to use an explicit brightness argument, i.e. using
`sudo msiklm <your-colors> high`
also does not work?
While resolving the original issue I implemented two ways how the colors are set to improve the device compatibility, thus proving the intensity argument is used as the control switch between the two options.

**Comment by Kaki-In** [comment]
Hy, 
The msiklm command works perfectly, with all intensities, but not the "rgb" one... so we cannot use rgb colors, just pre-defined colors. 

I have done some tests, and interrumpting "while true;do sudo msiklm 0xffcf03;done" sometimes works if we interrupt it... so I imagine it is an error of default colors (the keyboard seems to flicker while the command is running)... how can I fix it?

**Comment by Gibtnix** [comment]
Well, the additional modes might not be supported by all keyboards, but I don't know that for sure, it's just a personal guess.

Regarding the interrupted commands: I do not know in which actual "state" the keyboard remains if you interrupt the command setting. Maybe the remaining part of the buffer is not send to the keyboard and is treated as zero-only? But it's just a guess, too. I to simply stick with the commands that work for you.
